# Generated by Django 3.2.7 on 2022-09-18 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_auto_20220919_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(default='piece', on_delete=django.db.models.deletion.CASCADE, to='Store.unit_type'),
        ),
    ]
