# Generated by Django 3.2.7 on 2022-10-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_alter_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_value',
            field=models.IntegerField(default=0),
        ),
    ]
